const GET_OFFERS = `GET_OFFERS`;
const CHANGE_CURRENT_CITY = `CHANGE_CURRENT_CITY`;
const CHANGE_CURRENT_SORT = `CHANGE_CURRENT_SORT`;

export {
  GET_OFFERS,
  CHANGE_CURRENT_CITY,
  CHANGE_CURRENT_SORT
};
