const ActionType = {
  FETCH_DATA_REQUEST: `FETCH_DATA_REQUEST`,
  FETCH_DATA_SUCCESS: `FETCH_DATA_SUCCESS`,
  FETCH_OFFERS_SUCCESS: `FETCH_OFFERS_SUCCESS`,
  GET_CITIES: `GET_CITIES`,
  SET_CURRENT_CITY: `SET_CURRENT_CITY`,
  SET_CURRENT_SORT: `SET_CURRENT_SORT`
};

export default ActionType;
