const ActionType = {
  FETCH_DATA_REQUEST: `FETCH_DATA_REQUEST`,
  FETCH_DATA_SUCCESS: `FETCH_DATA_SUCCESS`,
  FETCH_OFFERS_SUCCESS: `FETCH_OFFERS_SUCCESS`,
  SET_CITIES: `SET_CITIES`,
  SET_CURRENT_CITY: `SET_CURRENT_CITY`,
  SET_CURRENT_SORT: `SET_CURRENT_SORT`,
  FETCH_LOGIN_SUCCESS: `FETCH_LOGIN_SUCCESS`,
  FETCH_LOGIN_FAILURE: `FETCH_LOGIN_FAILURE`,
  FETCH_OFFERS_NEARBY_SUCCESS: `FETCH_OFFERS_NEARBY_SUCCESS`,
  FETCH_REVIEWS_SUCCESS: `FETCH_REVIEWS_SUCCESS`
};

export default ActionType;
